#!/bin/bash
SOURCE="${1}"
TARGET="${2}"
PATTERN="${3:-*}"
mkdir -p "${TARGET}"

patterns_exist() {
    ls "${1}" &> /dev/null
    return $?
}

if patterns_exist ${SOURCE}/common/${PATTERN}; then
  cp -R ${SOURCE}/common/${PATTERN} ${TARGET}
fi

if [[ -n ${LCP_PROJECT_ENVIRONMENT} ]] && patterns_exist ${SOURCE}/${LCP_PROJECT_ENVIRONMENT}/${PATTERN}; then
  cp -rf ${SOURCE}/${LCP_PROJECT_ENVIRONMENT}/${PATTERN} ${TARGET}
fi
